[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "r2dnsort"
version = "0.1.0"
description = "Simple yet flexible natural sorting in Rust, exposed to Python"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.maturin]
features = ["python-ext"]
module-name = "r2dnsort"
